# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build dactyl_manuform 4x5_3'
on:
  - push
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["handwired/dactyl_manuform/4x5_3"]'
