# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build choc-skeletyl'
on:
  - push
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["handwired/choc_skeletyl"]'
      merge: '[
        "qmk/qmk_firmware/master",
        "qmk/qmk_firmware/develop"
      ]'
